@id = 1
@port = 80

### POST /clientes/{{id}}/transacoes
POST http://localhost:{{port}}/clientes/{{id}}/transacoes
Content-Type: application/json

{
  "valor": 10,
  "tipo": "d",
  "descricao": "debitar"
}

### POST /clientes/{{id}}/transacoes
POST http://localhost:{{port}}/clientes/{{id}}/transacoes
Content-Type: application/json

{
  "valor": 100,
  "tipo": "c",
  "descricao": "creditar"
}

### GET /clientes/{{id}}/extrato
GET http://localhost:{{port}}/clientes/{{id}}/extrato
