@id = 1
@port = 80

### POST /clientes/{{id}}/transacoes
POST http://localhost:{{port}}/clientes/{{id}}/transacoes
Content-Type: application/json

{
  "valor": 1,
  "tipo": "d",
  "descricao": "segunda"
}

### POST /clientes/{{id}}/transacoes
POST http://localhost:{{port}}/clientes/{{id}}/transacoes
Content-Type: application/json

{
  "valor": 1,
  "tipo": "c",
  "descricao": "X_8080_X"
}

### GET /clientes/{{id}}/extrato
GET http://localhost:{{port}}/clientes/{{id}}/extrato



### GET /lock
GET http://localhost:{{port}}/lock

### POST /lock
POST http://localhost:{{port}}/lock

### POST /unlock
POST http://localhost:{{port}}/unlock


