version: '3.5'

x-resources-api: &resources-api
  resources:
    limits:
      cpus: '0.2'
      memory: 50M

x-resources-db: &resources-db
  resources:
    limits:
      cpus: '0.9'
      memory: 400M

x-resources-nginx: &resources-nginx
  resources:
    limits:
      cpus: '0.2'
      memory: 50M

x-api: &api
  build: .
  depends_on:
    db:
      condition: service_healthy
  env_file:
    - .env
  volumes:
    - ./temp/postgres:/temp
  deploy:
    <<: *resources-api

services:
  api01:
    <<: *api
    environment:
      HTTP_PORT: 8080
    volumes:
      - ./temp:/temp
    ports:
      - "8080:8080"

  api02:
    <<: *api
    environment:
      HTTP_PORT: 8081
    volumes:
      - ./temp:/temp
    ports:
      - "8081:8081"

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ./temp/8080:/temp/8080
      - ./temp/8081:/temp/8081
    deploy:
      <<: *resources-nginx

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    command: |
      postgres 
      -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
      - ./temp/postgres:/var/run/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      <<: *resources-db

networks:
  default:
    driver: bridge
    name: rinhanet