-- CLIENTE
CREATE UNLOGGED TABLE IF NOT EXISTS C (
     I SMALLINT,
     L INT NOT NULL,
     S INT DEFAULT 0 CONSTRAINT V check (S >= (L*-1))
);
CREATE INDEX PK_X ON C (I) INCLUDE (S);

INSERT INTO C (I, L) VALUES (1, 1000*100),(2, 800*100),(3, 10000*100),(4, 100000*100),(5, 5000*100);

-- TRANSACAO
CREATE UNLOGGED TABLE IF NOT EXISTS T (
    I SMALLINT NOT NULL,
    V INT NOT NULL,
    P CHAR(1) NOT NULL,
    D VARCHAR(10) NOT NULL,
    R BIGINT default (extract(epoch from now()) * 1000)
);

CREATE INDEX C_X ON T (I);
CREATE INDEX R_X ON T (R DESC);
CLUSTER T USING C_X;



